name: Deploy to pages
on:
  push:
    branches: [master]
    tags:
      - "deploy-*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      NEXT_PUBLIC_BASE_PATH: /portfolio
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: bahmutov/npm-install@v1
      
      - run: yarn tsc

      - name: Build project
        run: yarn build

      # - name: Export static files
      #   run: yarn export

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out